import type { Metadata } from "next";
import {Lato } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import ThemeProvider from "@/context/Theme";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700", "900"], // puedes agregar los que necesites
});

export const metadata: Metadata = {
  title: "Armaco",
  description: "Generated by create next app",
  openGraph: {
    title: "Wordle Armaco",
    description: "Adivina el personaje en este divertido reto diario. ¡Ponte a prueba!",
    url: "https://armacowordle.vercel.app/",
    siteName: "Wordle Armaco",
    images: [
      {
        url: "https://armacowordle.vercel.app/og-image.png",
        width: 1200,
        height: 630,
        alt: "Vista previa del juego Wordle Armaco",
      },
    ],
    locale: "es_MX",
    type: "website",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${lato.variable} antialiased bg-white text-black dark:bg-[#131416] dark:text-white`}
      >
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

