import type { Metadata } from "next";
import {Lato } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import ThemeProvider from "@/context/Theme";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700", "900"], // puedes agregar los que necesites
});

export const metadata: Metadata = {
  title: "Armaco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${lato.variable} antialiased bg-white text-black dark:bg-[#131416] dark:text-white`}
      >
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

